# coding=UTF8
## This file is part of VideoTester
## See http://video-tester.googlecode.com for more information
## Copyright 2011 Iñaki Úcar <i.ucar86@gmail.com>
## This program is published under a GPLv3 license

# Description: run parallel tests with multiple .conf files (generated by test-generate-conf.py)

from subprocess import Popen

VT = './VT'
conf_path = 'test/'
tests = 2
processes = []

for i in range(0, tests):
    test = conf_path + 'test-' + str(i) + '.conf'
    print 'Running ' + test
    processes.append(Popen([VT, 'client', '-c', test]))
for process in processes:
    process.wait()
print "\nFinished"