#! /usr/bin/env python
# coding=UTF8

from VideoTester.config import parseArgs, initLogger, VTLOG
from sys import exit

if __name__ == '__main__':
    args = parseArgs()
    initLogger(args)
    if args.mode == "server":
        from VideoTester.config import SERVERIP, SERVERPORT
        from VideoTester.core import Server
        from SimpleXMLRPCServer import SimpleXMLRPCServer
        server = SimpleXMLRPCServer((SERVERIP, SERVERPORT), logRequests=False)
        server.register_instance(Server())
        try:
            print 'Use Control-C to exit'
            server.serve_forever()
        except KeyboardInterrupt:
            VTLOG.info("Exiting...")
    else:
        from os import getuid
        if getuid() != 0:
            VTLOG.error("You need administrator privileges to run this program as client")
            exit()
        if args.gui:
            from VideoTester.gui import ClientGUI
            client = ClientGUI(0)
            client.MainLoop()
        else:
            from VideoTester.config import CONF
            from VideoTester.core import Client
            if args.conf:
                CONF = args.conf
            client = Client(CONF)
            client.run()
        VTLOG.info("Exiting...")