#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Tue Mar  8 22:15:01 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class VTframe(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: VTframe.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.vtmenubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Select files...", "", wx.ITEM_NORMAL)
        wxglade_tmp_menu.AppendSeparator()
        wxglade_tmp_menu.Append(wx.NewId(), "Exit", "", wx.ITEM_NORMAL)
        self.vtmenubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.NewId(), "Run...", "", wx.ITEM_NORMAL)
        self.vtmenubar.Append(wxglade_tmp_menu, "Run")
        self.SetMenuBar(self.vtmenubar)
        # Menu Bar end
        self.vtstatusbar = self.CreateStatusBar(1, 0)
        self.tabs = wx.Notebook(self, -1, style=0)
        self.options_tab = wx.Panel(self.tabs, -1)
        self.video_label = wx.StaticText(self.options_tab, -1, "Choose a video:")
        self.video = wx.Choice(self.options_tab, -1, choices=["video0"])
        self.codec_label = wx.StaticText(self.options_tab, -1, "Choose a codec:")
        self.codec = wx.Choice(self.options_tab, -1, choices=["h263", "h264", "mpeg4", "theora"])
        self.bitrate_label = wx.StaticText(self.options_tab, -1, "Select the bitrate:")
        self.bitrate = wx.Slider(self.options_tab, -1, 128, 64, 2048, style=wx.SL_HORIZONTAL|wx.SL_LABELS)
        self.sizer_2_staticbox = wx.StaticBox(self.options_tab, -1, "Video options:")
        self.iface_label = wx.StaticText(self.options_tab, -1, "Interface:")
        self.iface = wx.TextCtrl(self.options_tab, -1, "eth0")
        self.ip_label = wx.StaticText(self.options_tab, -1, "Server IP:")
        self.ip = wx.TextCtrl(self.options_tab, -1, "0.0.0.0")
        self.port_label = wx.StaticText(self.options_tab, -1, "Server port:")
        self.port = wx.TextCtrl(self.options_tab, -1, "8554")
        self.protocols = wx.RadioBox(self.options_tab, -1, "Protocol:", choices=["UDP unicast", "TCP"], majorDimension=2, style=wx.RA_SPECIFY_COLS)
        self.sizer_3_staticbox = wx.StaticBox(self.options_tab, -1, "Net options:")
        self.delta = wx.CheckBox(self.options_tab, -1, "Delta")
        self.jitter = wx.CheckBox(self.options_tab, -1, "Jitter")
        self.skew = wx.CheckBox(self.options_tab, -1, "Skew")
        self.bandwidth = wx.CheckBox(self.options_tab, -1, "Bandwidth")
        self.plr = wx.CheckBox(self.options_tab, -1, "Packet Loss Rate")
        self.pld = wx.CheckBox(self.options_tab, -1, "Packet Loss Distribution")
        self.sizer_4_staticbox = wx.StaticBox(self.options_tab, -1, "QoS measures:")
        self.ypsnr = wx.CheckBox(self.options_tab, -1, "Y-PSNR")
        self.upsnr = wx.CheckBox(self.options_tab, -1, "U-PSNR")
        self.vpsnr = wx.CheckBox(self.options_tab, -1, "V-PSNR")
        self.sizer_5_staticbox = wx.StaticBox(self.options_tab, -1, "Video quality measures:")
        self.log_tab = wx.Panel(self.tabs, -1)
        self.log = wx.TextCtrl(self.log_tab, -1, "Log messages:\n----------------\n", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.results_tab = wx.Panel(self.tabs, -1)
        self.video_tab = wx.Panel(self.tabs, -1)
        self.label_2 = wx.StaticText(self.video_tab, -1, "Reference video (without codec degradation):")
        self.original_video = wx.Button(self.video_tab, -1, "Play")
        self.label_3 = wx.StaticText(self.video_tab, -1, "Reference video (with codec degradation):")
        self.coded_video = wx.Button(self.video_tab, -1, "Play")
        self.label_4 = wx.StaticText(self.video_tab, -1, "Received video:")
        self.received_video = wx.Button(self.video_tab, -1, "Play")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnSelect, id=-1)
        self.Bind(wx.EVT_MENU, self.OnExit, id=-1)
        self.Bind(wx.EVT_MENU, self.OnRun, id=-1)
        self.Bind(wx.EVT_BUTTON, self.onPlay, self.original_video)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: VTframe.__set_properties
        self.SetTitle("Video Tester")
        self.SetSize((800, 600))
        self.Hide()
        self.vtstatusbar.SetStatusWidths([-1])
        # statusbar fields
        vtstatusbar_fields = ["VT Client"]
        for i in range(len(vtstatusbar_fields)):
            self.vtstatusbar.SetStatusText(vtstatusbar_fields[i], i)
        self.video_label.SetMinSize((140, 17))
        self.video.SetMinSize((120, 25))
        self.video.SetSelection(0)
        self.codec_label.SetMinSize((140, 17))
        self.codec.SetMinSize((120, 25))
        self.codec.SetSelection(0)
        self.bitrate_label.SetMinSize((140, 17))
        self.bitrate.SetMinSize((230, 50))
        self.iface_label.SetMinSize((140, 17))
        self.iface.SetMinSize((80, 25))
        self.ip_label.SetMinSize((140, 17))
        self.ip.SetMinSize((150, 25))
        self.port_label.SetMinSize((140, 17))
        self.protocols.SetSelection(0)
        self.results_tab.Hide()
        self.received_video.Enable(False)
        self.video_tab.Hide()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: VTframe.__do_layout
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(3, 2, 5, 0)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.GridSizer(2, 2, 3, 3)
        self.sizer_5_staticbox.Lower()
        sizer_5 = wx.StaticBoxSizer(self.sizer_5_staticbox, wx.HORIZONTAL)
        grid_sizer_4 = wx.GridSizer(4, 3, 0, 0)
        self.sizer_4_staticbox.Lower()
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.HORIZONTAL)
        grid_sizer_3 = wx.GridSizer(6, 1, 0, 0)
        self.sizer_3_staticbox.Lower()
        sizer_3 = wx.StaticBoxSizer(self.sizer_3_staticbox, wx.HORIZONTAL)
        grid_sizer_2 = wx.GridSizer(4, 1, 0, 0)
        sizer_11 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_2_staticbox.Lower()
        sizer_2 = wx.StaticBoxSizer(self.sizer_2_staticbox, wx.HORIZONTAL)
        grid_sizer_5 = wx.GridSizer(3, 1, 0, 0)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_6.Add(self.video_label, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_6.Add(self.video, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_5.Add(sizer_6, 1, wx.EXPAND, 0)
        sizer_7.Add(self.codec_label, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_7.Add(self.codec, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_5.Add(sizer_7, 1, wx.EXPAND, 0)
        sizer_8.Add(self.bitrate_label, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_8.Add(self.bitrate, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_5.Add(sizer_8, 1, wx.EXPAND, 0)
        sizer_2.Add(grid_sizer_5, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        sizer_9.Add(self.iface_label, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_9.Add(self.iface, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(sizer_9, 1, wx.EXPAND, 0)
        sizer_10.Add(self.ip_label, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_10.Add(self.ip, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(sizer_10, 1, wx.EXPAND, 0)
        sizer_11.Add(self.port_label, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_11.Add(self.port, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_2.Add(sizer_11, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.protocols, 0, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_3.Add(grid_sizer_2, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.delta, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_3.Add(self.jitter, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_3.Add(self.skew, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_3.Add(self.bandwidth, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_3.Add(self.plr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_3.Add(self.pld, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_4.Add(grid_sizer_3, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)
        grid_sizer_4.Add(self.ypsnr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_4.Add(self.upsnr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_4.Add(self.vpsnr, 0, wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        sizer_5.Add(grid_sizer_4, 1, wx.EXPAND, 0)
        sizer_1.Add(sizer_5, 1, wx.EXPAND, 0)
        self.options_tab.SetSizer(sizer_1)
        sizer_13.Add(self.log, 1, wx.EXPAND|wx.ADJUST_MINSIZE, 0)
        self.log_tab.SetSizer(sizer_13)
        grid_sizer_1.Add(self.label_2, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.original_video, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_3, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.coded_video, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.label_4, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        grid_sizer_1.Add(self.received_video, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL|wx.ADJUST_MINSIZE, 0)
        self.video_tab.SetSizer(grid_sizer_1)
        self.tabs.AddPage(self.options_tab, "Configuration")
        self.tabs.AddPage(self.log_tab, "Log")
        self.tabs.AddPage(self.results_tab, "Results")
        self.tabs.AddPage(self.video_tab, "Video")
        sizer_12.Add(self.tabs, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_12)
        self.Layout()
        self.Centre()
        # end wxGlade

    def OnSelect(self, event): # wxGlade: VTframe.<event_handler>
        print "Event handler `OnSelect' not implemented!"
        event.Skip()

    def OnExit(self, event): # wxGlade: VTframe.<event_handler>
        print "Event handler `OnExit' not implemented!"
        event.Skip()

    def OnRun(self, event): # wxGlade: VTframe.<event_handler>
        print "Event handler `OnRun' not implemented!"
        event.Skip()

    def onPlay(self, event): # wxGlade: VTframe.<event_handler>
        print "Event handler `onPlay' not implemented!"
        event.Skip()

# end of class VTframe


class Clientgui(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        vtframe = VTframe(None, -1, "")
        self.SetTopWindow(vtframe)
        vtframe.Show()
        return 1

# end of class Clientgui

if __name__ == "__main__":
    clientgui = Clientgui(0)
    clientgui.MainLoop()
